### ISSUE TITLE
Unable to disable Ore Generation

### ISSUE THREAD

**Issue by mouse0270** [advaluti-dev/MaterialsExpanded#1]
I use a mod called "All the ore's" alongside of your mod. While working on my config files, I chose to use All the ore's world generation over yours because even though your mod provides more base metals to generate then ATOs, your mod purely generates ore's only in the overworld. So I wanted to disable any ore generation that overlaps, for example, copper and nickel.

I opened up your config, scrolled down to copper and changed `enableCopper = true` to `enableCopper = false` loaded up minecraft created a new world in creative and just started digging down until I found copper and it was copper from your mod.

I've attached my config file (had to rename ext to `txt` to upload it to github, but it is `toml` in my minecraft folder).
[matex-common.toml.txt](https://github.com/MichaelSixtyFour/MaterialsExpanded/files/5822580/matex-common.toml.txt)

**Comment by MichaelSixtyFour** [comment]
Fixed in 1.16.4-v1.8.3, thank you!
