### ISSUE TITLE
[Bug] Failed to create mod instance crash

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [advaluti-dev/MaterialsExpanded#3]
https://pastebin.com/RVTQyWsx
1.16.5, Forge 36.0.11
Seems to crash with latest 1.8.3

**Comment by Aspyro** [comment]
Same problem as above
https://gist.github.com/Aspyro/6f6ce93122495f4359288ca8663aad67
Minecraft version 1.16.4
Forge Version 35.1.37
MatEx version : 1.8.3

**Comment by MichaelSixtyFour** [comment]
Fixed in release 1.16.x-v1.8.4, sorry about that!
