### ISSUE TITLE
General ideas to improve the mod

### ISSUE THREAD

**Issue by Aspyro** [advaluti-dev/MaterialsExpanded#4]
These are the things I thought about during the configuration of a modpack using your mod as the single one adding ores :

1. Add back the possibility to tweak the minimum Y-level of the ores as the maximum is already present.
2. Add the possibility to change the stats of the armors and tools (including mortars and hammers).
3. Add the possibility to enable/disable all the dusts, plates, nuggets, rods and gears independantly (like you did for the charcoal nuggets). Of course, if the general config is set as _disabled_, that would have priority over a single one.
4. Add the possibility to generate the ores in other rocks (stone, granite, diorite, andesite) or in other dimensions (Nether, End). However this would certainly require the creation of appropriate texture and might be a lot of work. More work if there is the possibility to tweak the Y-levels in those dimensions too.
5. Add a chance to get 1 dust when distroying ores in an explosion (maybe for vanilla resources too) as this is "partially destroyed". That (of course) would be disable automatically when dusts are disabled.
6. In the description of the config file, add what mining level correspond to what tool (if i'm right something like "0 = empty hand" or "4 = diamond pickaxe"). Just once as a global note would be good I think

**Comment by Aspyro** [comment]
One more thing : Add tags to the items
Currently I need (i.e.) to list all the rods to disable them. Using the tag would be so much more effective

**Comment by MichaelSixtyFour** [comment]
All the items should have tags under MaterialsExpanded/src/main/resources/data/forge/tags/

**Comment by michaelocurtis** [comment]
Point 1 is now issue #18
Point 2 is now issue #9 and #11
Point 3 is now issue #20
Point 4 is now issue #14, #15 and #19
Point 5 is now issue #13
Point 6 is now issue #12

No guarantee that all this will be worked on, but should make it easier to work on over time.

**Comment by Michael-Curtis0** [comment]
Point 6 is now issue #12
