### ISSUE TITLE
Recipe Problem : Tin axe and Tin shovel

### ISSUE THREAD

**Issue by Aspyro** [advaluti-dev/MaterialsExpanded#5]
Tin axe has 2 recipes : one for a Tin axe, the other for what should be a Tin shovel.
Tin shovel has no recipe.

See the first and the third craft on the screenshot

![2021-02-12_14 37 19](https://user-images.githubusercontent.com/37420016/107774966-025e4880-6d40-11eb-9f92-6e7f2ac55aeb.png)

**Comment by Aspyro** [comment]
Made a pull request to correct that issue :-)

**Comment by MichaelSixtyFour** [comment]
Thanks!
